name: CICD-PR

on:
  push:
    branches: [master, feature/cicd-pr]
  pull_request:
    branches: [master, feature/cicd-pr]

env:
  JWT_SECRET=secret
  DATABASE_URI=mongodb://0.0.0.0:27017
  DB_NAME=register_movie
  OMDB_API_KEY=7104c460


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: npm install and test
      run: |
        npm install
        npm test



